### PR TITLE
Adding version to module.json and fix alignement of composer.json

### PR DESCRIPTION
**Pull request by Grummfy**
* Align json file
* Force to have a version in the module created or updated. Without this => error in admin, and a module should always have a version ;)

### CODE REVIEW

**Comment by Grummfy** [comment]
There is at least 3 tools called php-cs-fixer (without counting forks), can you indicated the one you are thinking?

No other comment?

**Comment by nWidart** [comment]
It's all explained in the contributing.md file.. https://github.com/AsgardCms/Workshop/blob/develop/CONTRIBUTING.md

**Comment by Grummfy** [comment]
Sorry have skipped the contributing file .
Fixed done

**Comment by nWidart** [comment]
Thank you :+1:

**Pull request merged**
